version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    command: "--global-response-templating --verbose"
    volumes:
      - $PWD/wiremock:/home/wiremock
    ports:
      - "5050:8080"