open-weather-api:
  baseUrl: ${OPENWEATHER_URL:http://localhost:5050}
  endpoint: "/onecall?lat={lat}&lon={lon}&exclude={part}&appid={APIKEY}"
  url: "https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&exclude={part}&appid={APIKEY}"
  key: ${OPENWEATHER_API_KEY}


wiremock:
  host: localhost
  port: 5050