spring:
  application:
    name: condition-checker

open-weather-api:
  baseUrl: "https://api.openweathermap.org/data/3.0/onecall"
  endpoint: "/timemachine?lat=53.39293&lon=-2.98532&dt=%s&appid=%s"
#  endpoint: "/timemachine?lat=53.39293&lon=-2.98532&dt={EPOCH_TIME}&appid={APIKEY}"

  key: ${OPENWEATHER_API_KEY}

wiremock:
  host: ${WIREMOCK_HOST:localhost}
  port: ${WIREMOCK_PORT:5050}

